server:
  port: 8088

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USUARIO-SERVICE
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: CALIFICACION-SERVICE
          uri: lb://CALIFICACION-SERVICE
          predicates:
            - Path=/qualifications/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka